# Generated by Django 5.1.4 on 2025-01-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0006_admissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
