# Generated by Django 5.1.4 on 2025-01-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0007_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissions',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='date_of_admission',
        ),
        migrations.AddField(
            model_name='admissions',
            name='hostel',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='admissions',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='admission_number',
            field=models.CharField(max_length=100),
        ),
    ]
