# Generated by Django 5.1.4 on 2025-01-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0008_rename_name_admissions_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='Unnamed Assignment', max_length=100),
        ),
    ]
