# Generated by Django 5.1.4 on 2025-01-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbhs', '0009_alter_assignment_options_alter_assignment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='form',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='name',
        ),
    ]
